# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('five-g-aka-example', ['netanim','mmwave','applications','network','core','internet', 'config-store','stats','five-g-aka'])
    obj.source = 'five-g-aka-example.cc'
    obj = bld.create_ns3_program('one-g', ['netanim','mmwave','applications','network','core','internet', 'config-store','stats','five-g-aka'])
    obj.source = 'one-g.cc'

